[package]
name = "rust_exercises"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pig_latin"
path = "src/pig_latin/main.rs"

[[bin]]
name = "median_mode"
path = "src/median_mode/main.rs"

[[bin]]
name = "departments"
path = "src/departments/main.rs"

[dependencies]
